interface TestSuite {
  id: string
  moduleName: string
  totalTests: number
  passedTests: number
  failedTests: number
  coverage: number
  lastRun: string
  status: 'passing' | 'failing' | 'running'
  discrepancies: number
}

interface ShadowTestResult {
  id: string
  scenario: string
  legacyOutput: any
  newOutput: any
  matchPercentage: number
  status: 'match' | 'mismatch' | 'error'
}

const mockTestSuites: TestSuite[] = [
  { id: 't1', moduleName: 'UserAuth', totalTests: 234, passedTests: 234, failedTests: 0, coverage: 94.5, lastRun: '2 hours ago', status: 'passing', discrepancies: 0 },
  { id: 't2', moduleName: 'PaymentService', totalTests: 189, passedTests: 186, failedTests: 3, coverage: 87.2, lastRun: '5 hours ago', status: 'failing', discrepancies: 3 },
  { id: 't3', moduleName: 'OrderProcessor', totalTests: 312, passedTests: 312, failedTests: 0, coverage: 91.8, lastRun: '1 day ago', status: 'passing', discrepancies: 0 },
  { id: 't4', moduleName: 'InventoryAPI', totalTests: 156, passedTests: 156, failedTests: 0, coverage: 89.3, lastRun: '2 days ago', status: 'passing', discrepancies: 0 },
  { id: 't5', moduleName: 'NotificationService', totalTests: 98, passedTests: 95, failedTests: 3, coverage: 82.1, lastRun: 'Running now...', status: 'running', discrepancies: 0 },
]

const mockShadowResults: ShadowTestResult[] = [
  { id: 's1', scenario: 'User login with valid credentials', legacyOutput: { success: true, token: 'abc123' }, newOutput: { success: true, token: 'xyz789' }, matchPercentage: 100, status: 'match' },
  { id: 's2', scenario: 'Payment processing - credit card', legacyOutput: { status: 'approved', amount: 99.99 }, newOutput: { status: 'approved', amount: 99.99 }, matchPercentage: 100, status: 'match' },
  { id: 's3', scenario: 'Order calculation with discount', legacyOutput: { total: 89.99, discount: 10 }, newOutput: { total: 91.99, discount: 8 }, matchPercentage: 95.2, status: 'mismatch' },
  { id: 's4', scenario: 'Inventory check for SKU-12345', legacyOutput: { available: true, quantity: 42 }, newOutput: { available: true, quantity: 42 }, matchPercentage: 100, status: 'match' },
  { id: 's5', scenario: 'Email notification trigger', legacyOutput: { sent: true, template: 'order_confirm' }, newOutput: { sent: false, error: 'SMTP timeout' }, matchPercentage: 0, status: 'error' },
]

export default function EquivalenceEngine() {
  const totalTests = mockTestSuites.reduce((acc, suite) => acc + suite.totalTests, 0)
  const totalPassed = mockTestSuites.reduce((acc, suite) => acc + suite.passedTests, 0)
  const overallPassRate = (totalPassed / totalTests) * 100

  return (
    <div className="space-y-6 fade-in">
      {/* Overview Stats */}
      <div className="grid grid-cols-4 gap-4">
        <div className="bg-gradient-to-br from-green-500/10 to-emerald-500/10 rounded-xl p-6 border border-green-500/30">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-lg bg-green-500/20 flex items-center justify-center text-2xl">✓</div>
            <div>
              <p className="text-sm text-gray-400">Pass Rate</p>
              <p className="text-2xl font-bold text-green-400">{overallPassRate.toFixed(1)}%</p>
            </div>
          </div>
          <p className="text-xs text-gray-500">Across all test suites</p>
        </div>

        <div className="bg-gradient-to-br from-blue-500/10 to-cyan-500/10 rounded-xl p-6 border border-blue-500/30">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-lg bg-blue-500/20 flex items-center justify-center text-2xl">📋</div>
            <div>
              <p className="text-sm text-gray-400">Total Tests</p>
              <p className="text-2xl font-bold text-blue-400">{totalTests.toLocaleString()}</p>
            </div>
          </div>
          <p className="text-xs text-gray-500">Auto-generated by AI</p>
        </div>

        <div className="bg-gradient-to-br from-purple-500/10 to-pink-500/10 rounded-xl p-6 border border-purple-500/30">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-lg bg-purple-500/20 flex items-center justify-center text-2xl">👥</div>
            <div>
              <p className="text-sm text-gray-400">Coverage</p>
              <p className="text-2xl font-bold text-purple-400">88.9%</p>
            </div>
          </div>
          <p className="text-xs text-gray-500">Average code coverage</p>
        </div>

        <div className="bg-gradient-to-br from-orange-500/10 to-red-500/10 rounded-xl p-6 border border-orange-500/30">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-lg bg-orange-500/20 flex items-center justify-center text-2xl">⚠️</div>
            <div>
              <p className="text-sm text-gray-400">Discrepancies</p>
              <p className="text-2xl font-bold text-orange-400">6</p>
            </div>
          </div>
          <p className="text-xs text-gray-500">Require investigation</p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-6">
        {/* Test Suites */}
        <div className="col-span-2 space-y-4">
          <div className="flex items-center justify-between">
            <h4 className="text-lg font-semibold text-white">Test Suites</h4>
            <button className="px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors text-sm">
              🔄 Run All Tests
            </button>
          </div>

          {mockTestSuites.map((suite) => (
            <div key={suite.id} className="bg-dark-card rounded-xl p-5 border border-gray-700 hover:border-gray-600 transition-all">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className={`w-3 h-3 rounded-full ${
                    suite.status === 'passing' ? 'bg-green-500' :
                    suite.status === 'failing' ? 'bg-red-500 animate-pulse' :
                    'bg-yellow-500 animate-pulse'
                  }`} />
                  <div>
                    <h5 className="font-semibold text-white">{suite.moduleName}</h5>
                    <p className="text-sm text-gray-400">Last run: {suite.lastRun}</p>
                  </div>
                </div>
                <div className="flex items-center gap-6">
                  <div className="text-right">
                    <p className="text-sm text-gray-400">Tests</p>
                    <p className="text-white font-medium">
                      <span className="text-green-400">{suite.passedTests}</span>
                      <span className="text-gray-500"> / </span>
                      <span className={suite.failedTests > 0 ? 'text-red-400' : 'text-white'}>{suite.totalTests}</span>
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm text-gray-400">Coverage</p>
                    <p className="text-white font-medium">{suite.coverage}%</p>
                  </div>
                  <button className="px-4 py-2 bg-gray-700 text-white rounded-lg hover:bg-gray-600 transition-colors text-sm">
                    View Details
                  </button>
                </div>
              </div>

              {/* Coverage Bar */}
              <div className="relative h-2 bg-gray-700 rounded-full overflow-hidden">
                <div 
                  className={`absolute top-0 left-0 h-full rounded-full transition-all duration-500 ${
                    suite.coverage >= 90 ? 'bg-green-500' :
                    suite.coverage >= 70 ? 'bg-yellow-500' :
                    'bg-red-500'
                  }`}
                  style={{ width: `${suite.coverage}%` }}
                ></div>
              </div>

              {suite.failedTests > 0 && (
                <div className="mt-3 p-3 bg-red-500/10 border border-red-500/30 rounded-lg">
                  <p className="text-sm text-red-400">
                    ⚠️ {suite.failedTests} failing test{suite.failedTests > 1 ? 's' : ''} detected. 
                    <button className="ml-2 text-primary hover:underline">View failures →</button>
                  </p>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Shadow Testing Results */}
        <div className="space-y-4">
          <h4 className="text-lg font-semibold text-white">Shadow Test Results</h4>
          
          <div className="bg-dark-card rounded-xl p-4 border border-gray-700">
            <p className="text-sm text-gray-400 mb-4">
              Running legacy and refactored code in parallel to verify behavioral equivalence
            </p>

            <div className="space-y-3">
              {mockShadowResults.map((result) => (
                <div key={result.id} className="p-3 bg-gray-800/50 rounded-lg border-l-4" style={{ 
                  borderColor: result.status === 'match' ? '#10b981' : 
                               result.status === 'mismatch' ? '#f59e0b' : '#ef4444' 
                }}>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm font-medium text-white">{result.scenario}</span>
                    <span className={`text-xs px-2 py-0.5 rounded ${
                      result.status === 'match' ? 'bg-green-500/20 text-green-400' :
                      result.status === 'mismatch' ? 'bg-yellow-500/20 text-yellow-400' :
                      'bg-red-500/20 text-red-400'
                    }`}>
                      {result.status.toUpperCase()}
                    </span>
                  </div>
                  
                  {result.status !== 'match' && (
                    <div className="mt-2 text-xs space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="text-gray-500">Legacy:</span>
                        <code className="text-orange-400 bg-gray-900 px-2 py-0.5 rounded">
                          {JSON.stringify(result.legacyOutput)}
                        </code>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="text-gray-500">New:</span>
                        <code className={`px-2 py-0.5 rounded ${
                          result.status === 'error' ? 'text-red-400 bg-gray-900' : 'text-blue-400 bg-gray-900'
                        }`}>
                          {JSON.stringify(result.newOutput)}
                        </code>
                      </div>
                      {result.matchPercentage < 100 && result.matchPercentage > 0 && (
                        <div className="pt-1">
                          <span className="text-gray-500">Match: </span>
                          <span className="text-yellow-400">{result.matchPercentage}%</span>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>

            <button className="w-full mt-4 px-4 py-2 bg-primary/20 text-primary rounded-lg hover:bg-primary/30 transition-colors text-sm">
              View All Shadow Tests
            </button>
          </div>

          {/* AI Insights */}
          <div className="bg-gradient-to-br from-accent/10 to-purple-500/10 rounded-xl p-4 border border-accent/30">
            <h4 className="font-semibold text-white mb-3 flex items-center gap-2">
              🤖 AI Insights
            </h4>
            <div className="space-y-3 text-sm">
              <p className="text-gray-300">
                <span className="text-accent">•</span> PaymentService has 3 failing tests related to rounding precision in currency calculations
              </p>
              <p className="text-gray-300">
                <span className="text-accent">•</span> NotificationService shadow test failure appears to be infrastructure-related (SMTP), not logic
              </p>
              <p className="text-gray-300">
                <span className="text-accent">•</span> Recommend increasing test coverage on OrderProcessor edge cases
              </p>
            </div>
            <button className="w-full mt-3 px-4 py-2 bg-accent/20 text-accent rounded-lg hover:bg-accent/30 transition-colors text-sm">
              Generate Fix Suggestions
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
